security:

    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        secured_area:
            pattern: ^/
            form_login:
                login_path: app_login
                default_target_path: /courses
                check_path: app_login
                enable_csrf: true
            entry_point: App\Security\LoginFormAuthenticator
            logout:
                path: app_logout
                target: homepage

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
            

        main:
            lazy: true
            provider: app_user_provider
            form_login:
                always_use_default_target_path: true
                default_target_path: /courses
                login_path: app_login
                check_path: app_login


    access_control:
        - { path: '^/teacher/', roles: ROLE_TEACHER }
        # - { path: ^/profile, roles: ROLE_USER }

# This is only used in a test environment
# You don't need to add these configurations in a production environment
when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
