controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
course_new:
    path: '/teacher/course/new'
    controller: App\Controller\CourseController::create
course_update:
    path: 'teacher/course/{id}/update'
    controller: App\Controller\CourseController::update
course_view:
    path: '/course/{id}'
    controller: App\Controller\CourseController::view
course_delete:
    path: '/course/{id}/delete'
    controller: App\Controller\CourseController::delete
section_new:
    path: '/teacher/section/new'
    controller: App\Controller\SectionController::new
course_list:
    path: '/courses'
    controller: App\Controller\EnrollmentController::listCourses

enroll_course:
    path: '/enroll/{courseId}'
    controller: App\Controller\EnrollmentController::enrollCourse

edit_course:
    path: '/teacher/course/{id}/edit'
    controller: 'App\Controller\CourseController::edit'
    
delete_course:
    path: '/teacher/course/{id}/delete'
    controller: 'App\Controller\CourseController::delete'